<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!-- Generated by TLex Lexicography Software (build Aug 18 2022 21:18:34) -->
<!-- Generated on Thu Apr 13 07:28:38 2023 -->
<!-- TshwaneDJe HLT - XML version 1.10 -->
<!-- ExportListValuesByText: OFF -->
<!-- UseZeroWidthSpacesToPreventConversionOfPCDataToElements: OFF -->
<!DOCTYPE tshwanelexicon [
<!ELEMENT tshwanelexicon (dtd,styleset*,Dictionary)>
<!ELEMENT dtd (specialtypes?,dtdlist*,xreftypes*)>
<!ELEMENT dtdlist (dtdlistitem*,listlabelset*)>
<!ELEMENT dtdlistitem EMPTY>
<!ELEMENT listlabelset (listlabel*)>
<!ELEMENT listlabel EMPTY>
<!ELEMENT xreftypes (xreftype*,xreflabelset*)>
<!ELEMENT xreftype EMPTY>
<!ELEMENT xreflabelset (xreflabel*)>
<!ELEMENT xreflabel EMPTY>
<!ELEMENT specialtypes (special*)>
<!ELEMENT special EMPTY>
<!ELEMENT styleset (order,style*)>
<!ELEMENT order (order_element*)>
<!ELEMENT order_element (order_item*)>
<!ELEMENT order_item EMPTY>
<!ELEMENT style (style_autonumber*)>
<!ELEMENT style_autonumber EMPTY>
<!ELEMENT Dictionary (Language+)>
<!ELEMENT Language (Lemma*)>
<!ELEMENT Lemma (References*,Sense*,Subentry*)>
<!ELEMENT Sense (References*,Definition*,TE*,Example*,Subentry*,Sense*)>
<!ELEMENT Example EMPTY>
<!ELEMENT Subentry (References*,Sense*)>
<!ELEMENT Definition EMPTY>
<!ELEMENT TE EMPTY>
<!ELEMENT References (reflemma*)>
<!ELEMENT reflemma (refsense*)>
<!ELEMENT refsense EMPTY>
<!ATTLIST dtdlist id CDATA #REQUIRED>
<!ATTLIST dtdlist name CDATA #REQUIRED>
<!ATTLIST dtdlistitem id CDATA #REQUIRED>
<!ATTLIST dtdlistitem name CDATA #REQUIRED>
<!ATTLIST listlabelset name CDATA #REQUIRED>
<!ATTLIST listlabel listitemid CDATA #REQUIRED>
<!ATTLIST listlabel name CDATA #REQUIRED>
<!ATTLIST xreftype id CDATA #REQUIRED>
<!ATTLIST xreftype name CDATA #REQUIRED>
<!ATTLIST xreflabelset name CDATA #REQUIRED>
<!ATTLIST xreflabel xreftypeid CDATA #REQUIRED>
<!ATTLIST xreflabel labels CDATA #REQUIRED>
<!ATTLIST xreflabel labelp CDATA #REQUIRED>
<!ATTLIST reflemma lemmaid CDATA #REQUIRED>
<!ATTLIST reflemma type CDATA #REQUIRED>
<!ATTLIST refsense senseid CDATA #REQUIRED>
<!ATTLIST special type CDATA #REQUIRED>
<!ATTLIST special section CDATA #REQUIRED>
<!ATTLIST special attr CDATA #REQUIRED>
<!ATTLIST special elem CDATA #REQUIRED>
<!ATTLIST styleset name CDATA #IMPLIED>
<!ATTLIST order_element elementname CDATA #REQUIRED>
<!ATTLIST order_item type CDATA #REQUIRED>
<!ATTLIST order_item name CDATA #REQUIRED>
<!ATTLIST order_item visible CDATA #REQUIRED>
<!ATTLIST style type CDATA #IMPLIED>
<!ATTLIST style elementname CDATA #IMPLIED>
<!ATTLIST style attributename CDATA #IMPLIED>
<!ATTLIST style style CDATA #IMPLIED>
<!ATTLIST style font CDATA #IMPLIED>
<!ATTLIST style fontsize CDATA #IMPLIED>
<!ATTLIST style bold CDATA #IMPLIED>
<!ATTLIST style italic CDATA #IMPLIED>
<!ATTLIST style underline CDATA #IMPLIED>
<!ATTLIST style superscript CDATA #IMPLIED>
<!ATTLIST style subscript CDATA #IMPLIED>
<!ATTLIST style smallcaps CDATA #IMPLIED>
<!ATTLIST style caps CDATA #IMPLIED>
<!ATTLIST style colourf CDATA #IMPLIED>
<!ATTLIST style colourb CDATA #IMPLIED>
<!ATTLIST style beforei CDATA #IMPLIED>
<!ATTLIST style afteri CDATA #IMPLIED>
<!ATTLIST style beforeo CDATA #IMPLIED>
<!ATTLIST style aftero CDATA #IMPLIED>
<!ATTLIST style beforeg CDATA #IMPLIED>
<!ATTLIST style afterg CDATA #IMPLIED>
<!ATTLIST style between CDATA #IMPLIED>
<!ATTLIST style_autonumber type CDATA #IMPLIED>
<!ATTLIST style_autonumber always CDATA #IMPLIED>
<!ATTLIST style_autonumber breadth CDATA #IMPLIED>
<!ATTLIST style_autonumber depth CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary Name CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary Description CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary CreatedBy CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary Copyright CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary URL CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Dictionary SoundPath CDATA #IMPLIED>
<!ATTLIST Dictionary id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Language Name CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#IMPLIED,ltr -->
<!ATTLIST Language Options CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Language AlphabetQuicklinks CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Language xml:lang CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Language SearchScript CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Language ClickScript CDATA #IMPLIED>
<!ATTLIST Language id CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma Incomplete CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#REQUIRED,ltr -->
<!ATTLIST Lemma LemmaSign CDATA #REQUIRED>
<!-- ATTDATA NDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma HomonymNumber CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma Pronunciation CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma Deriv CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma Etymology CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Lemma Notes CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#DATECHANGED,ltr -->
<!ATTLIST Lemma Modified CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#DATECREATED,ltr -->
<!ATTLIST Lemma Created CDATA #IMPLIED>
<!-- ATTDATA LNDATA,Usage label,#IMPLIED,ltr -->
<!ATTLIST Lemma UsageLabel CDATA #IMPLIED>
<!-- ATTDATA LNDATA,Part of speech,#IMPLIED,ltr -->
<!ATTLIST Lemma PartOfSpeech CDATA #IMPLIED>
<!ATTLIST Lemma id CDATA #IMPLIED>
<!-- ATTDATA NDATA,,#AUTONUMBER,ltr -->
<!ATTLIST Sense SenseNumber CDATA #IMPLIED>
<!-- ATTDATA LNDATA,Usage label,#IMPLIED,ltr -->
<!ATTLIST Sense UsageLabel CDATA #IMPLIED>
<!-- ATTDATA LNDATA,Part of speech,#IMPLIED,ltr -->
<!ATTLIST Sense PartOfSpeech CDATA #IMPLIED>
<!-- ATTDATA LNSDATA,Semantic Domains,#IMPLIED,ltr -->
<!ATTLIST Sense SemDomain CDATA #IMPLIED>
<!ATTLIST Sense id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Example Example CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Example Translation CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Example Source CDATA #IMPLIED>
<!ATTLIST Example id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Subentry LemmaSign CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Subentry Pronunciation CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Subentry Deriv CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#IMPLIED,ltr -->
<!ATTLIST Subentry Etymology CDATA #IMPLIED>
<!-- ATTDATA LNDATA,Usage label,#IMPLIED,ltr -->
<!ATTLIST Subentry UsageLabel CDATA #IMPLIED>
<!-- ATTDATA LNDATA,Part of speech,#IMPLIED,ltr -->
<!ATTLIST Subentry PartOfSpeech CDATA #IMPLIED>
<!ATTLIST Subentry id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#NORMAL,ltr -->
<!ATTLIST Definition Definition CDATA "">
<!ATTLIST Definition id CDATA #IMPLIED>
<!-- ATTDATA CDATA,,#NORMAL,ltr -->
<!ATTLIST TE TE CDATA "">
<!ATTLIST TE id CDATA #IMPLIED>
<!ATTLIST References id CDATA #IMPLIED>
<!ENTITY ndash "–">
<!ENTITY mdash "—">
<!ENTITY lsquo "‘">
<!ENTITY rsquo "’">
<!ENTITY ldquo "“">
<!ENTITY rdquo "”">
<!ENTITY bull "•">
<!ENTITY hellip "…">
<!ENTITY trade "™">
<!ENTITY dagger "†">
<!ENTITY Dagger "‡">
<!ENTITY lsaquo "‹">
<!ENTITY rsaquo "›">
<!ENTITY sp " ">
<!ENTITY nbsp " ">
<!ENTITY ensp " ">
<!ENTITY emsp " ">
<!ENTITY pound "£">
<!ENTITY copy "©">
<!ENTITY reg "®">
<!ENTITY tshwanelex__list__seperator ";">
]>
<tshwanelexicon>
<dtd>
	<specialtypes>
		<special type="0" section="2" attr="TE" elem="TE"/>
		<special type="2" section="2" attr="" elem="Sense"/>
		<special type="3" section="2" attr="LemmaSign" elem="Lemma"/>
		<special type="4" section="2" attr="Notes" elem="Lemma"/>
		<special type="0" section="3" attr="TE" elem="TE"/>
		<special type="2" section="3" attr="" elem="Sense"/>
		<special type="3" section="3" attr="LemmaSign" elem="Lemma"/>
		<special type="4" section="3" attr="Notes" elem="Lemma"/>
	</specialtypes>
	<dtdlist id="1" name="Usage label">
		<listlabelset name="1">
		</listlabelset>
		<listlabelset name="2">
		</listlabelset>
	</dtdlist>
	<dtdlist id="2" name="Part of speech">
		<dtdlistitem id="10" name="abbreviation"/>
		<dtdlistitem id="8" name="adjective"/>
		<dtdlistitem id="38" name="ADV"/>
		<dtdlistitem id="33" name="adv"/>
		<dtdlistitem id="9" name="adverb"/>
		<dtdlistitem id="14" name="concord"/>
		<dtdlistitem id="12" name="conjunction"/>
		<dtdlistitem id="55" name="COUNT"/>
		<dtdlistitem id="34" name="DEM"/>
		<dtdlistitem id="46" name="DIR"/>
		<dtdlistitem id="36" name="dir"/>
		<dtdlistitem id="44" name="EXC"/>
		<dtdlistitem id="26" name="ha"/>
		<dtdlistitem id="19" name="ho"/>
		<dtdlistitem id="29" name="ho hi"/>
		<dtdlistitem id="32" name="ho ma"/>
		<dtdlistitem id="30" name="ho mag"/>
		<dtdlistitem id="39" name="ho ma g"/>
		<dtdlistitem id="20" name="ho mahi"/>
		<dtdlistitem id="51" name="ho ma hi"/>
		<dtdlistitem id="54" name="ho ma k"/>
		<dtdlistitem id="53" name="ho maka"/>
		<dtdlistitem id="21" name="i"/>
		<dtdlistitem id="15" name="idiom"/>
		<dtdlistitem id="52" name="i ma"/>
		<dtdlistitem id="22" name="i na"/>
		<dtdlistitem id="13" name="interjection"/>
		<dtdlistitem id="47" name="INTEROG"/>
		<dtdlistitem id="35" name="loc"/>
		<dtdlistitem id="18" name="ma"/>
		<dtdlistitem id="40" name="manga"/>
		<dtdlistitem id="27" name="nanga"/>
		<dtdlistitem id="48" name="NCL"/>
		<dtdlistitem id="3" name="noun"/>
		<dtdlistitem id="25" name="npf"/>
		<dtdlistitem id="42" name="NUM"/>
		<dtdlistitem id="50" name="num"/>
		<dtdlistitem id="17" name="o"/>
		<dtdlistitem id="23" name="part"/>
		<dtdlistitem id="45" name="plant"/>
		<dtdlistitem id="4" name="pl noun"/>
		<dtdlistitem id="28" name="PRO"/>
		<dtdlistitem id="11" name="pronoun"/>
		<dtdlistitem id="16" name="proverb"/>
		<dtdlistitem id="37" name="Q"/>
		<dtdlistitem id="49" name="RFLX"/>
		<dtdlistitem id="5" name="verb"/>
		<dtdlistitem id="7" name="verb intransitive"/>
		<dtdlistitem id="6" name="verb transitive"/>
		<dtdlistitem id="43" name="vpf"/>
		<dtdlistitem id="24" name="vsf"/>
		<dtdlistitem id="41" name="ya"/>
		<listlabelset name="Tobelo PoS">
			<listlabel listitemid="10" name="abbreviation"/>
			<listlabel listitemid="8" name="adjective"/>
			<listlabel listitemid="38" name="ADV"/>
			<listlabel listitemid="33" name="adv"/>
			<listlabel listitemid="9" name="adverb"/>
			<listlabel listitemid="14" name="concord"/>
			<listlabel listitemid="12" name="conjunction"/>
			<listlabel listitemid="55" name="COUNT"/>
			<listlabel listitemid="34" name="DEM"/>
			<listlabel listitemid="46" name="DIR"/>
			<listlabel listitemid="36" name="dir"/>
			<listlabel listitemid="44" name="EXC"/>
			<listlabel listitemid="26" name="ha"/>
			<listlabel listitemid="19" name="ho"/>
			<listlabel listitemid="29" name="ho hi"/>
			<listlabel listitemid="32" name="ho ma"/>
			<listlabel listitemid="30" name="ho mag"/>
			<listlabel listitemid="39" name="ho ma g"/>
			<listlabel listitemid="20" name="ho mahi"/>
			<listlabel listitemid="51" name="ho ma hi"/>
			<listlabel listitemid="54" name="ho ma k"/>
			<listlabel listitemid="53" name="ho maka"/>
			<listlabel listitemid="21" name="i"/>
			<listlabel listitemid="15" name="idiom"/>
			<listlabel listitemid="52" name="i ma"/>
			<listlabel listitemid="22" name="i na"/>
			<listlabel listitemid="13" name="interjection"/>
			<listlabel listitemid="47" name="INTEROG"/>
			<listlabel listitemid="35" name="loc"/>
			<listlabel listitemid="18" name="ma"/>
			<listlabel listitemid="40" name="manga"/>
			<listlabel listitemid="27" name="nanga"/>
			<listlabel listitemid="48" name="NCL"/>
			<listlabel listitemid="3" name="noun"/>
			<listlabel listitemid="25" name="npf"/>
			<listlabel listitemid="42" name="NUM"/>
			<listlabel listitemid="50" name="num"/>
			<listlabel listitemid="17" name="o"/>
			<listlabel listitemid="23" name="part"/>
			<listlabel listitemid="45" name="plant"/>
			<listlabel listitemid="4" name="pl noun"/>
			<listlabel listitemid="28" name="PRO"/>
			<listlabel listitemid="11" name="pronoun"/>
			<listlabel listitemid="16" name="proverb"/>
			<listlabel listitemid="37" name="Q"/>
			<listlabel listitemid="49" name="RFLX"/>
			<listlabel listitemid="5" name="verb"/>
			<listlabel listitemid="7" name="verb intransitive"/>
			<listlabel listitemid="6" name="verb transitive"/>
			<listlabel listitemid="43" name="vpf"/>
			<listlabel listitemid="24" name="vsf"/>
			<listlabel listitemid="41" name="ya"/>
		</listlabelset>
		<listlabelset name="English PoS">
			<listlabel listitemid="10" name="abbreviation"/>
			<listlabel listitemid="8" name="adjective"/>
			<listlabel listitemid="38" name="ADV"/>
			<listlabel listitemid="33" name="adv"/>
			<listlabel listitemid="9" name="adverb"/>
			<listlabel listitemid="14" name="concord"/>
			<listlabel listitemid="12" name="conjunction"/>
			<listlabel listitemid="55" name="COUNT"/>
			<listlabel listitemid="34" name="DEM"/>
			<listlabel listitemid="46" name="DIR"/>
			<listlabel listitemid="36" name="dir"/>
			<listlabel listitemid="44" name="EXC"/>
			<listlabel listitemid="26" name="ha"/>
			<listlabel listitemid="19" name="ho"/>
			<listlabel listitemid="29" name="ho hi"/>
			<listlabel listitemid="32" name="ho ma"/>
			<listlabel listitemid="30" name="ho mag"/>
			<listlabel listitemid="39" name="ho ma g"/>
			<listlabel listitemid="20" name="ho mahi"/>
			<listlabel listitemid="51" name="ho ma hi"/>
			<listlabel listitemid="54" name="ho ma k"/>
			<listlabel listitemid="53" name="ho maka"/>
			<listlabel listitemid="21" name="i"/>
			<listlabel listitemid="15" name="idiom"/>
			<listlabel listitemid="52" name="i ma"/>
			<listlabel listitemid="22" name="i na"/>
			<listlabel listitemid="13" name="interjection"/>
			<listlabel listitemid="47" name="INTEROG"/>
			<listlabel listitemid="35" name="loc"/>
			<listlabel listitemid="18" name="ma"/>
			<listlabel listitemid="40" name="manga"/>
			<listlabel listitemid="27" name="nanga"/>
			<listlabel listitemid="48" name="NCL"/>
			<listlabel listitemid="3" name="noun"/>
			<listlabel listitemid="25" name="npf"/>
			<listlabel listitemid="42" name="NUM"/>
			<listlabel listitemid="50" name="num"/>
			<listlabel listitemid="17" name="o"/>
			<listlabel listitemid="23" name="part"/>
			<listlabel listitemid="45" name="plant"/>
			<listlabel listitemid="4" name="pl noun"/>
			<listlabel listitemid="28" name="PRO"/>
			<listlabel listitemid="11" name="pronoun"/>
			<listlabel listitemid="16" name="proverb"/>
			<listlabel listitemid="37" name="Q"/>
			<listlabel listitemid="49" name="RFLX"/>
			<listlabel listitemid="5" name="verb"/>
			<listlabel listitemid="7" name="verb intransitive"/>
			<listlabel listitemid="6" name="verb transitive"/>
			<listlabel listitemid="43" name="vpf"/>
			<listlabel listitemid="24" name="vsf"/>
			<listlabel listitemid="41" name="ya"/>
		</listlabelset>
	</dtdlist>
	<dtdlist id="56" name="Semantic Domains">
		<dtdlistitem id="57" name="nautical"/>
		<dtdlistitem id="58" name="plant"/>
		<dtdlistitem id="59" name="insect"/>
		<dtdlistitem id="60" name="body part"/>
		<dtdlistitem id="61" name="earth"/>
		<dtdlistitem id="62" name="color"/>
		<dtdlistitem id="63" name="time"/>
		<dtdlistitem id="64" name="kin"/>
		<dtdlistitem id="65" name="hunting"/>
		<dtdlistitem id="66" name="food"/>
		<dtdlistitem id="67" name="animal"/>
		<dtdlistitem id="68" name="fish"/>
		<dtdlistitem id="69" name="fishing"/>
		<dtdlistitem id="70" name="dir"/>
		<dtdlistitem id="71" name="tool"/>
		<dtdlistitem id="72" name="household"/>
		<dtdlistitem id="73" name="birds"/>
		<dtdlistitem id="74" name="sky"/>
		<dtdlistitem id="75" name="magic"/>
		<dtdlistitem id="76" name="num"/>
		<dtdlistitem id="77" name="weaving"/>
		<dtdlistitem id="78" name="clothing"/>
		<dtdlistitem id="79" name="house"/>
		<dtdlistitem id="80" name="bird"/>
		<dtdlistitem id="81" name="people"/>
		<dtdlistitem id="82" name="NUM"/>
		<dtdlistitem id="83" name="med"/>
		<listlabelset name="Semantic Domains (English)">
			<listlabel listitemid="57" name="nautical"/>
			<listlabel listitemid="58" name="plant"/>
			<listlabel listitemid="59" name="insect"/>
			<listlabel listitemid="60" name="body part"/>
			<listlabel listitemid="61" name="earth"/>
			<listlabel listitemid="62" name="color"/>
			<listlabel listitemid="63" name="time"/>
			<listlabel listitemid="64" name="kin"/>
			<listlabel listitemid="65" name="hunting"/>
			<listlabel listitemid="66" name="food"/>
			<listlabel listitemid="67" name="animal"/>
			<listlabel listitemid="68" name="fish"/>
			<listlabel listitemid="69" name="fishing"/>
			<listlabel listitemid="70" name="dir"/>
			<listlabel listitemid="71" name="tool"/>
			<listlabel listitemid="72" name="household"/>
			<listlabel listitemid="73" name="birds"/>
			<listlabel listitemid="74" name="sky"/>
			<listlabel listitemid="75" name="magic"/>
			<listlabel listitemid="76" name="num"/>
			<listlabel listitemid="77" name="weaving"/>
			<listlabel listitemid="78" name="clothing"/>
			<listlabel listitemid="79" name="house"/>
			<listlabel listitemid="80" name="bird"/>
			<listlabel listitemid="81" name="people"/>
			<listlabel listitemid="82" name="NUM"/>
			<listlabel listitemid="83" name="med"/>
		</listlabelset>
		<listlabelset name="-">
			<listlabel listitemid="57" name="nautical"/>
			<listlabel listitemid="58" name="plant"/>
			<listlabel listitemid="59" name="insect"/>
			<listlabel listitemid="60" name="body part"/>
			<listlabel listitemid="61" name="earth"/>
			<listlabel listitemid="62" name="color"/>
			<listlabel listitemid="63" name="time"/>
			<listlabel listitemid="64" name="kin"/>
			<listlabel listitemid="65" name="hunting"/>
			<listlabel listitemid="66" name="food"/>
			<listlabel listitemid="67" name="animal"/>
			<listlabel listitemid="68" name="fish"/>
			<listlabel listitemid="69" name="fishing"/>
			<listlabel listitemid="70" name="dir"/>
			<listlabel listitemid="71" name="tool"/>
			<listlabel listitemid="72" name="household"/>
			<listlabel listitemid="73" name="birds"/>
			<listlabel listitemid="74" name="sky"/>
			<listlabel listitemid="75" name="magic"/>
			<listlabel listitemid="76" name="num"/>
			<listlabel listitemid="77" name="weaving"/>
			<listlabel listitemid="78" name="clothing"/>
			<listlabel listitemid="79" name="house"/>
			<listlabel listitemid="80" name="bird"/>
			<listlabel listitemid="81" name="people"/>
			<listlabel listitemid="82" name="NUM"/>
			<listlabel listitemid="83" name="med"/>
		</listlabelset>
	</dtdlist>
	<xreftypes>
		<xreftype id="1" name="Equivalence"/>
		<xreftype id="2" name="See"/>
		<xreftype id="3" name="Synonym"/>
		<xreftype id="4" name="Antonym"/>
		<xreftype id="5" name="Compare"/>
		<xreflabelset name="English">
			<xreflabel xreftypeid="1" labels="=" labelp="="/>
			<xreflabel xreftypeid="2" labels="SEE" labelp="SEE"/>
			<xreflabel xreftypeid="3" labels="SYNONYM" labelp="SYNONYMS"/>
			<xreflabel xreftypeid="4" labels="ANTONYM" labelp="ANTONYMS"/>
			<xreflabel xreftypeid="5" labels="COMPARE" labelp="COMPARE"/>
		</xreflabelset>
	</xreftypes>
</dtd>
<styleset name="Default styles">
	<order>
		<order_element elementname="Dictionary">
			<order_item type="element" name="Language" visible="1"/>
			<order_item type="attribute" name="Name" visible="1"/>
			<order_item type="attribute" name="Description" visible="1"/>
			<order_item type="attribute" name="CreatedBy" visible="1"/>
			<order_item type="attribute" name="Copyright" visible="1"/>
			<order_item type="attribute" name="URL" visible="1"/>
			<order_item type="attribute" name="SoundPath" visible="1"/>
		</order_element>
		<order_element elementname="Language">
			<order_item type="element" name="Lemma" visible="1"/>
			<order_item type="attribute" name="Name" visible="1"/>
			<order_item type="attribute" name="Options" visible="1"/>
			<order_item type="attribute" name="AlphabetQuicklinks" visible="1"/>
			<order_item type="attribute" name="xml:lang" visible="1"/>
			<order_item type="attribute" name="SearchScript" visible="1"/>
			<order_item type="attribute" name="ClickScript" visible="1"/>
		</order_element>
		<order_element elementname="Lemma">
			<order_item type="attribute" name="Incomplete" visible="1"/>
			<order_item type="attribute" name="LemmaSign" visible="1"/>
			<order_item type="attribute" name="HomonymNumber" visible="1"/>
			<order_item type="attribute" name="Pronunciation" visible="1"/>
			<order_item type="attribute" name="Deriv" visible="1"/>
			<order_item type="attribute" name="PartOfSpeech" visible="1"/>
			<order_item type="attribute" name="UsageLabel" visible="1"/>
			<order_item type="element" name="References" visible="1"/>
			<order_item type="element" name="Sense" visible="1"/>
			<order_item type="element" name="Subentry" visible="1"/>
			<order_item type="attribute" name="Etymology" visible="1"/>
			<order_item type="attribute" name="Notes" visible="1"/>
			<order_item type="attribute" name="Modified" visible="1"/>
			<order_item type="attribute" name="Created" visible="1"/>
		</order_element>
		<order_element elementname="Sense">
			<order_item type="attribute" name="SenseNumber" visible="1"/>
			<order_item type="attribute" name="PartOfSpeech" visible="1"/>
			<order_item type="attribute" name="UsageLabel" visible="1"/>
			<order_item type="element" name="References" visible="1"/>
			<order_item type="element" name="Definition" visible="1"/>
			<order_item type="element" name="TE" visible="1"/>
			<order_item type="element" name="Example" visible="1"/>
			<order_item type="element" name="Subentry" visible="1"/>
			<order_item type="element" name="Sense" visible="1"/>
			<order_item type="attribute" name="SemDomain" visible="1"/>
		</order_element>
		<order_element elementname="Example">
			<order_item type="attribute" name="Example" visible="1"/>
			<order_item type="attribute" name="Translation" visible="1"/>
			<order_item type="attribute" name="Source" visible="1"/>
		</order_element>
		<order_element elementname="Subentry">
			<order_item type="attribute" name="LemmaSign" visible="1"/>
			<order_item type="attribute" name="Pronunciation" visible="1"/>
			<order_item type="attribute" name="Deriv" visible="1"/>
			<order_item type="attribute" name="PartOfSpeech" visible="1"/>
			<order_item type="attribute" name="UsageLabel" visible="1"/>
			<order_item type="element" name="References" visible="1"/>
			<order_item type="element" name="Sense" visible="1"/>
			<order_item type="attribute" name="Etymology" visible="1"/>
		</order_element>
		<order_element elementname="Definition">
			<order_item type="attribute" name="Definition" visible="1"/>
		</order_element>
		<order_element elementname="TE">
			<order_item type="attribute" name="TE" visible="1"/>
		</order_element>
		<order_element elementname="References">
		</order_element>
	</order>
	<style type="element" elementname="Lemma" attributename="-1" style="Andika,14.000000,-1,-1,-1,-1,-1,-1,-1,000000,FFFFFF,,,,,,,,1,3,0.000000,-5.000000,5.000000,0.000000,4.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Lemma" attributename="LemmaSign" style=",-1.000000,1,-1,-1,-1,-1,-1,-1,000070,,,,,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Lemma" attributename="HomonymNumber" style=",8.000000,1,-1,-1,1,-1,-1,-1,000070,,,,,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Lemma" attributename="Pronunciation" style=",-1.000000,-1,1,-1,-1,-1,-1,-1,575757,, /,/,,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Lemma" attributename="Deriv" style=",-1.000000,1,-1,-1,-1,-1,-1,-1,460B00,, (=,),,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Lemma" attributename="Etymology" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,202020,, [,],,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Lemma" attributename="Notes" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,FD8668,, {,},,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Lemma" attributename="Modified" style=",9.000000,-1,-1,-1,-1,-1,-1,-1,888888,, [,],,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Lemma" attributename="Created" style=",9.000000,-1,1,-1,-1,-1,-1,-1,888888,, [,],,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="Sense" attributename="-1" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,062A06,,,,,,,,;,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="References" attributename="-1" style=",-1.000000,1,-1,-1,-1,-1,-1,-1,0C5252,,,,,, ,, ,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="Subentry" attributename="-1" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,880502,,,,,,,,&quot;,&quot;,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Subentry" attributename="LemmaSign" style=",-1.000000,1,-1,-1,-1,-1,-1,-1,,, ,,,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Subentry" attributename="Deriv" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,, (=,),,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Subentry" attributename="Pronunciation" style=",-1.000000,-1,1,-1,-1,-1,-1,-1,575757,, /,/,,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Subentry" attributename="Etymology" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,, ,,,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="Example" attributename="-1" style="Times New Roman,11.000000,-1,-1,-1,-1,-1,-1,-1,706D10,,,,,,:,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Example" attributename="Example" style=",-1.000000,-1,1,-1,-1,-1,-1,-1,,, ,,,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Example" attributename="Translation" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,, ,,,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Example" attributename="Source" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,, ,,,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="Definition" attributename="-1" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,128181,,,,,,,,;,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="attribute" elementname="Definition" attributename="Definition" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,,, ,,,,,,,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />
	<style type="element" elementname="TE" attributename="-1" style=",-1.000000,-1,-1,-1,-1,-1,-1,-1,066606,,,,,,,,&quot;,&quot;,0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,0.000000,000000,0,0.000000,"  />